### ISSUE TITLE
About the Dependencies

### ISSUE THREAD

**Issue by Peterxjerk** [despargy/maestro#1]
Hello, I am trying to Catkin make this package and there is a CMake Error:

CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "fusion" with any
  of the following names:

    fusionConfig.cmake
    fusion-config.cmake

I notice that you have added the fusion as the dependency in the CMakeLists.txt. Can you give me some suggestion to solve this problem? Is the fusion a ros package or something else?

**Comment by Peterxjerk** [comment]
Additionally, the include part in [include/Robot.h](https://github.com/despargy/maestro/blob/1e61571f0eb9b0c87bd210a4b7d5d0081a7931c2/include/Robot.h) #include <maestro/Foot.h> and [include/CommunicationHandler.h](https://github.com/despargy/maestro/blob/1e61571f0eb9b0c87bd210a4b7d5d0081a7931c2/include/CommunicationHandler.h) #include <maestro/LowCmdRos.h>, #include <maestro/LowStateRos.h>. It seems that these files are missing. I would appreciate it if you could help me to solve these problems.

**Comment by despargy** [comment]
> Hello, I am trying to Catkin make this package and there is a CMake Error:
> 
> CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package): Could not find a package configuration file provided by "fusion" with any of the following names:
> 
> ```
> fusionConfig.cmake
> fusion-config.cmake
> ```
> 
> I notice that you have added the fusion as the dependency in the CMakeLists.txt. Can you give me some suggestion to solve this problem? Is the fusion a ros package or something else?

I have just updated the Maestro package which will solve the fusion dependence issue. 
Thank you!

**Comment by despargy** [comment]
> Additionally, the include part in [include/Robot.h](https://github.com/despargy/maestro/blob/1e61571f0eb9b0c87bd210a4b7d5d0081a7931c2/include/Robot.h) #include <maestro/Foot.h> and [include/CommunicationHandler.h](https://github.com/despargy/maestro/blob/1e61571f0eb9b0c87bd210a4b7d5d0081a7931c2/include/CommunicationHandler.h) #include <maestro/LowCmdRos.h>, #include <maestro/LowStateRos.h>. It seems that these files are missing. I would appreciate it if you could help me to solve these problems.

Those are some old headers that they are not longer used. There is a new Maestro package version which will solve that issue.
If you have any further questions, please let me know!
Best regards,
Despina

**Comment by Peterxjerk** [comment]
Thanks for helping. I can run the package without adaptation in the simulation now, however, in the adaptation part I cannot find the contact.launch. I also cannot find it in the ProbabilisticContactEstimation package. Is there a mistake?

**Comment by Peterxjerk** [comment]
These are videos of the simulation and the real experiment without adaptation. It seems that the model is unstable in the gazebo. When I run the main_handler, the robot stands up when I press the Enter at the first time, however, it will fall down when I press the Enter again to start the control loop.

https://user-images.githubusercontent.com/64294923/231711315-937e3875-25b8-4a04-89f9-87f04010d3c4.mp4


https://user-images.githubusercontent.com/64294923/231711359-0de8b3ad-ee67-4ab1-b6c4-3f07a67a0fe5.mp4

**Comment by despargy** [comment]
> Thanks for helping. I can run the package without adaptation in the simulation now, however, in the adaptation part I cannot find the contact.launch. I also cannot find it in the ProbabilisticContactEstimation package. Is there a mistake?

Using https://github.com/MichaelMarav/ProbabilisticContactEstimation, you need to set this up.

**Comment by despargy** [comment]
> 

Dear,
Please make sure you follow the given instruction. 

| :exclamation:  This is very important   |
|-----------------------------------------|

> **Warning**  Before run experiments with the real robot Go1, first secure Unitree's Go1 EDU, ex. photo in Maestro package. 

It seems your real robot has no info about its model state (CoM position). Keep in mind that the provided controller is a closed-loop. The system should get info about the robot's model state. In case of real robot experiments, you should set the appropriate topic at line 39 of file 'CommunicationHandler.h'. 

Regarding the simulation, make sure that no other launch files connecting to the robot is running. 

Best regards,
Despina

**Comment by Peterxjerk** [comment]
I think that I have set up the package and catkin make it already.
![catkin_ws](https://user-images.githubusercontent.com/64294923/231733808-144fac9c-e6dc-4b4c-960d-9894e9da7c48.png)

According to your instruction, the second step to run the package with adaptation is $ roslaunch contact_estimation contact.launch
![Adaptation](https://user-images.githubusercontent.com/64294923/231734413-9b9ec7e3-22e8-49a8-838d-bd735312a374.png)

But I could not find the contact.launch file in https://github.com/MichaelMarav/ProbabilisticContactEstimation/tree/main/launch
There is only a launch file named [slip_experiment.launch]
![ProbabilisticContactEstimation](https://user-images.githubusercontent.com/64294923/231735121-6efa41d5-486f-496b-809e-873604cc2d5f.png)

**Comment by Peterxjerk** [comment]
Thanks for your suggestion. I run the simulation without adaptation. Is it in a right situation?
There are probably some issue in the attach file function, you can also see it in my goole drive.

https://drive.google.com/file/d/1Pl7B7PGIuUHm-0McvMx2TkNWT1unbe1l/view?usp=share_link

https://user-images.githubusercontent.com/64294923/231757010-89d7ce61-2ebf-44d0-8b54-542952f935f7.mp4

**Comment by despargy** [comment]
This is the expected robot response without adaptation, no issue can be found. The robot cannot follow the desired path in such slippery surfaces.  With adaptation, we are in the good position to overcome the last mentioned problem.

The next steps to follow regarding the simulation part with adaptation using the Probabilistic Contact Estimation package are: 
1. attach virtual IMU's on robot's legs.
2. publish the probability of slippage of each leg-imu using PCE package (`ProbabilisticContactEstimation`).

 I will make sure, during the next days, to publish another package helping you out with the simulation part regarding the `ProbabilisticContactEstimation` and `Maestro` simulation.

I'm kindly asking to open separate Github issues for different issue themes.

Thank you,
Despina

**Comment by Peterxjerk** [comment]
Ok. Thank you very much.
